### PR TITLE
Extend supplementary character support

### PR DESCRIPTION
**Pull request by nibe**
`Character/toLowerCase`, `Character/toUpperCase` and `Character/toTitleCase` support code points of supplementary characters so I removed the limitation to BMP using `char'`.

### CODE REVIEW

**Comment by daveyarwood** [comment]
Thanks for the PR! This seems like a good change to make. I think we should add a few test cases just to be certain that it works with characters above the BMP range.

**Comment by nibe** [comment]
There you go.

**Comment by daveyarwood** [comment]
Looks good, thanks again!

**Comment by nibe** [comment]
Thanks for the Clojars update!

`(char/upper-case "𐐬")` now returns `"𐐄"` instead of raising `IllegalArgumentException: Value out of range for char: 66564`, which will be useful for my project.

**Pull request merged**
